# Generated by Django 5.2 on 2026-05-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('capacidad_puestos', models.PositiveIntegerField()),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['fecha_inicio'],
            },
        ),
    ]