# Generated by Django 5.2.14 on 2026-05-17 20:14

import django.db.models.deletion
from django.db import migrations, models


def populate_categoria_temp(apps, schema_editor):
    Feria = apps.get_model('app', 'Feria')
    Categoria = apps.get_model('app', 'Categoria')

    for feria in Feria.objects.all():
        nombre_categoria = (feria.categoria or '').strip()
        if not nombre_categoria:
            continue

        categoria_obj, _ = Categoria.objects.get_or_create(nombre=nombre_categoria)
        feria.categoria_temp = categoria_obj
        feria.save(update_fields=['categoria_temp'])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='feria',
            name='categoria_temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ferias', to='app.categoria'),
        ),
        migrations.RunPython(populate_categoria_temp, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='feria',
            name='categoria',
        ),
        migrations.RenameField(
            model_name='feria',
            old_name='categoria_temp',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='feria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ferias', to='app.categoria'),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('edicion', models.DateField()),
                ('capacidad_puestos', models.PositiveIntegerField()),
                ('tiene_conexion_electrica', models.BooleanField(default=False)),
                ('feria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectores', to='app.feria')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('feria', 'nombre')},
            },
        ),
    ]
