# Generated by Django 5.2.14 on 2026-05-27 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='emprendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.emprendedor'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='feria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.feria'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resena',
            name='emprendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.emprendedor'),
        ),
        migrations.AddField(
            model_name='resena',
            name='visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.visitante'),
        ),
        migrations.AddField(
            model_name='sector',
            name='feria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectores', to='app.feria'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('feria', 'numero_puesto')},
        ),
        migrations.AlterUniqueTogether(
            name='resena',
            unique_together={('visitante', 'emprendedor')},
        ),
        migrations.AlterUniqueTogether(
            name='sector',
            unique_together={('feria', 'nombre')},
        ),
    ]
