# Generated by Django 5.2.14 on 2026-06-02 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('feria', 'emprendedor'), ('feria', 'numero_puesto')},
        ),
    ]
