# Generated by Django 5.2.14 on 2026-06-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='edicion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
