# Generated by Django 5.2.14 on 2026-05-20 19:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_populate_categoria_from_feria'),
        ('usuarios', '0002_remove_emprendedor_email_remove_visitante_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_puesto', models.PositiveIntegerField()),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('lista_espera', 'Lista de espera'), ('cancelada', 'Cancelada')], default='confirmada', max_length=20)),
                ('emprendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.emprendedor')),
                ('feria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.feria')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('feria', 'numero_puesto')},
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('puntuacion', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('emprendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.emprendedor')),
                ('feria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.feria')),
            ],
            options={
                'unique_together': {('feria', 'emprendedor')},
            },
        ),
    ]
