# Generated by Django 5.2.14 on 2026-06-05 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_inscripcion_unique_together'),
        ('app', '0003_alter_sector_edicion'),
    ]

    operations = [
    ]
