# Generated by Django 6.0.4 on 2026-06-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20260605_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='numero_puesto',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
