# Generated by Django 6.0.4 on 2026-06-12 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_inscripcion_numero_puesto'),
        ('usuarios', '0004_create_groups'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('feria', 'emprendedor')},
        ),
    ]
