# Generated by Django 5.2.14 on 2026-06-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_inscripcion_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='feria',
            name='edicion',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
