# Generated by Django 5.2.14 on 2026-05-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitante',
            name='usuario',
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('visitante', 'Visitante'), ('emprendedor', 'Emprendedor')], default='emprendedor', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
        migrations.DeleteModel(
            name='Visitante',
        ),
    ]
