# Generated by Django 5.2.14 on 2026-05-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprendedor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='email',
        ),
    ]
