# Generated by Django 5.2.14 on 2026-06-04 13:46


from django.db import migrations


class Migration(migrations.Migration):
    def create_groups(apps, schema_editor):
        Group = apps.get_model("auth", "Group")

        Group.objects.get_or_create(name="Admin")
        Group.objects.get_or_create(name="Visitante")
        Group.objects.get_or_create(name="Emprendedor")

    dependencies = [
        ('usuarios', '0003_notificacion_visitante'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
