# Generated by Django 5.2.14 on 2026-06-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_create_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
